---
title: "US Insurance EDA"
author: "Xiang Li"
date: "11/16/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(ggplot2)
library(arm)
library(rstanarm)
library(dplyr)  

insurance_raw <- read.csv("insurance.csv",header = T)
#age_range <- cut_interval(insurance$age, n = 6)
#bmi_range <- cut_interval(insurance$bmi, n = 5)

insurance <-insurance_raw %>% mutate(
  age_Group=case_when(
    age<=20 ~ "Group1",
    age>20 & age<=30 ~"Group2",
    age>30 & age<=40 ~"Group3",
    age>40 & age<=50 ~"Group4",
    age>50 & age<=60 ~"Group5",
    TRUE ~ "Group6"
  ),
  bmi_Group=case_when(
    bmi<=18.5 ~ "UnderWeight",
    bmi>18.5 & bmi<=24.9 ~"HealthyWeight",
    bmi>25 & bmi<=29.9 ~"OverWeight",
    TRUE ~ "Obese" 
  ),
  Sex=case_when(
    sex =="female"~0,
    TRUE ~ 1
  ),
  Region=case_when(
    region =="northwest" ~ 1,
    region =="northeast" ~ 2,
    region =="southwest" ~ 3,
    TRUE ~ 4
  ),
  Smoker=case_when(
    smoker =="no" ~ 0,
    TRUE ~ 1
  )
)



                                       
 
```

```{r}
hist(insurance$bmi)
hist(insurance$age)

vilion_plot1<-ggplot(data = insurance, aes(x=bmi_Group, y=charges, fill=bmi_Group)) +
  geom_violin(trim=FALSE)+ scale_fill_brewer(palette="Blues")+ 
 geom_boxplot(width=0.1, fill="white")+
  labs(title="Plot of charges by bmi_Group",x="bmi_Group", y = "Charges")+
  theme_classic()
vilion_plot1

vilion_plot2<-ggplot(data = insurance, aes(x=smoker, y=charges, fill=smoker)) +
  geom_violin(trim=FALSE)+ scale_fill_brewer(palette="Blues")+ 
 geom_boxplot(width=0.1, fill="white")+
  labs(title="Plot of charges by smokers",x="smoker", y = "Charges")+
  theme_classic()
vilion_plot2

vilion_plot3<-ggplot(data = insurance, aes(x=region, y=charges, fill=region)) +
  geom_violin(trim=FALSE)+ scale_fill_brewer(palette="Blues")+ 
 geom_boxplot(width=0.1, fill="white")+
  labs(title="Plot of charges by region",x="region", y = "Charges")+
  theme_classic()
vilion_plot3

vilion_plot4<-ggplot(data = insurance, aes(x=age_Group, y=charges, fill=age_Group)) +
  geom_violin(trim=FALSE)+ scale_fill_brewer(palette="Blues")+ 
 geom_boxplot(width=0.1, fill="white")+
  labs(title="Plot of charges by Age Group",x="Age Group", y = "Charges")+
  theme_classic()
vilion_plot4
```

```{r}
insurance_numeric <- insurance[, c('age','Sex','Region','Smoker','children','bmi','charges')]
library(corrplot)

corrplot(cor(insurance_numeric), type = "upper", order = "hclust", 
         tl.col = "black", tl.srt = 45)
corrplot(cor(insurance_numeric), is.corr = FALSE, method = "square")

corrplot(cor(insurance_numeric))


library(ggcorrplot)
ggcorrplot(cor(insurance_numeric), 
           hc.order = TRUE, 
           type = "lower",
           lab = TRUE)
```


```{r}
p <- ggplot(insurance, aes(age,charges)) + 
  geom_jitter(aes(colour=smoker))+geom_smooth(method = "loess",formula ="y ~ x")
p

p+ facet_wrap(~smoker)
```

```{r}
ggplot(data = insurance)+
  aes(bmi,log(charges))+
  geom_point(aes(color = age_Group),alpha = 0.3)+
  labs(title="number of visits vs number of comments",x="log(BMI)",y="log(Charges)")+
  geom_smooth(aes(color = age_Group),method = "lm",se=F,formula = y~x)+
  facet_wrap(~smoker)
```
```{r}
ggplot(data = insurance)+
  aes(bmi,log(charges))+
  geom_point(aes(color = smoker),alpha = 0.3)+
  labs(title="number of visits vs number of comments",x="log(BMI)",y="log(Charges)")+
  geom_smooth(aes(color = smoker),method = "lm",se=F,formula = y~x)+
  facet_wrap(~age_Group)
```

```{r}
plot <- ggplot(data = insurance)+
  aes(log(bmi),log(charges))+
  geom_point(aes(color = age_Group),alpha = 0.3)+
  labs(title="number of visits vs number of comments",x="log(BMI)",y="log(Charges)")+
  geom_smooth(aes(color = age_Group),method = "lm",se=F,formula = y~x)
  plot+ facet_wrap(~sex)
  plot+ facet_wrap(~region)
  plot+ facet_wrap(~children)
  plot+ facet_wrap(~smoker)
 
```

```{r}

plot2 <- ggplot(data = insurance)+
  aes(age,log(charges))+
  geom_point(aes(color = bmi_Group),alpha = 0.3)+
  labs(title="AGE vs Charges",x="Age",y="log(Charges)")+
  geom_smooth(aes(color = bmi_Group),method = "lm",se=F,formula = y~x)

  plot2 + facet_wrap(~smoker)
  plot2 + facet_wrap(~region)
  plot2 + facet_wrap(~children)
   plot2 + facet_grid(~sex)
```
```{r}
plot3 <- ggplot(data = insurance)+
  aes(age,log(charges))+
  geom_point(aes(color = region),alpha = 0.3)+
  labs(title="AGE vs Charges",x="Age",y="log(Charges)")+
  geom_smooth(aes(color = region),method = "lm",se=F,formula = y~x)

  plot3 + facet_wrap(~smoker)
  plot3 + facet_wrap(~region)
  plot3 + facet_wrap(~children)
   plot3 + facet_grid(~sex)
```
```{r}
plot4 <- ggplot(data = insurance)+
  aes(age,log(charges))+
  geom_point(aes(color = factor(children)),alpha = 0.3)+
  labs(title="AGE vs Charges",x="Age",y="log(Charges)")+
  geom_smooth(aes(color = factor(children)),method = "lm",se=F,formula = y~x)

  plot4 + facet_wrap(~smoker)
  plot4 + facet_wrap(~region)
  plot4 + facet_wrap(~children)
   plot4 + facet_grid(~sex)
```

```{r}
plot4 <- ggplot(data = insurance)+
  aes(age,log(charges))+
  geom_point(aes(color = factor(children)),alpha = 0.3)+
  labs(title="AGE vs Charges",x="Age",y="log(Charges)")+
  geom_smooth(aes(color = factor(children)),method = "lm",se=F,formula = y~x)

  plot4 + facet_wrap(~smoker)
  plot4 + facet_wrap(~region)
  plot4 + facet_wrap(~children)
   plot4 + facet_grid(~sex)
```


```{r}
#age <- cut(insurance$age,breaks=c(18,23,29,35,41,46,52,58,54))
#age
log_charges <- log(insurance$charges)
children <- factor(children)
#fit_model<- stan_lmer(log_charges~sex+smoker+children+region+(1+smoker|age_Group)+(1+smoker|bmi_Group),data=insurance,refresh=0)

#display(fit_model)
#coef(fit_model)
#summary(fit_model)

fit_model_1<- lmer(log_charges~sex+smoker+children+region+(1+smoker|age_Group)+(1+smoker|bmi_Group),data=insurance)

coef(fit_model_1)
summary(fit_model_1)

residul_plot <- plot(fit_model_1)
qq_plot     <- qqmath(fit_model_1)
residul_plot
qq_plot 

```
```{r}
fit_model_2<- lmer(log_charges~sex+smoker+children+region+(1+smoker|age_Group)+(1+sex|age_Group)+(1+smoker|bmi_Group)+(1+sex|bmi_Group),data=insurance)
display(fit_model_2)
coef(fit_model_2)
summary(fit_model_2)
round(summary(fit_model_2)$coefficient, digits = 2)
```



```
```{r}
fit_model_3<- lmer(log_charges~sex+Smoker+(1+Smoker+sex|age_Group)+(1+smoker+region+age|bmi_Group),data=insurance)
display(fit_model_3)
coef(fit_model_3)
summary(fit_model_3)
round(summary(fit_model_3)$coefficient, digits = 2)

round(ranef(fit_model_3)$Team, digits = 2)
```


```{r}
pp_check(fit_model)
```

```{r}

```


